version: '2.2'

services:
  replication-manager:
    build: replication-manager
    image: desec/replication-manager:latest
    restart: "no"
    depends_on:
    - dbmaster
    volumes:
    - ${DESECSTACK_REPLICATION_MANAGER_CERTS}:/usr/src/app/certs
    environment:
    - DESECSTACK_DBMASTER_PASSWORD_replication_manager
    networks:
    - rearmaster
    logging:
      driver: "json-file"

