version: '2'

services:

  elasticsearch:
    build: elasticsearch
    ports:
    - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    build: logstash/
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    build: kibana
    depends_on:
    - elasticsearch
    ports:
    - "5601:5601"

  www:
    build: www
    image: desec/dedyn-www:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ${DESECSTACK_CERT_FOLDER}:/etc/ssl/private:ro
    - ./www/html:/usr/share/nginx/html:ro
    depends_on:
    - static
    - api
    - logstash
    mac_address: 06:42:ac:10:00:80
    networks:
      front:
        ipv4_address: 172.16.0.128
        ipv6_address: ${DESECSTACK_IPV6_ADDRESS}
#      - back2 # TODO add when https://github.com/docker/docker/issues/27101 is fixed
    logging:
      driver: "syslog"
      options:
        tag: "desec/www"
        syslog-address: "tcp://localhost:5000"

  static:
    build: static
    image: desec/dedyn-static:latest
    networks:
    - front # TODO change to back2 when https://github.com/docker/docker/issues/27101 is fixed
    depends_on:
    - logstash
    logging:
      driver: "syslog"
      options:
        tag: "desec/static"
        syslog-address: "tcp://localhost:5000"

  dbapi:
    build: dbapi
    image: desec/dedyn-dbapi:latest
    volumes:
    - dbapi_mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${DESECSTACK_DBAPI_PASSWORD_root}
    - DESECSTACK_DBAPI_PASSWORD_desec
    depends_on:
    - logstash
    networks:
    - back1
    logging:
      driver: "syslog"
      options:
        tag: "desec/dbapi"
#        syslog-address: "tcp://localhost:5000"

  dblord:
    build: dblord
    image: desec/dedyn-dblord:latest
    volumes:
    - dblord_mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${DESECSTACK_DBLORD_PASSWORD_root}
    - DESECSTACK_DBLORD_PASSWORD_pdns
    - DESECSTACK_DBLORD_PASSWORD_poweradmin
    - DESECSTACK_DEVADMIN_PASSWORD_poweradmin
    depends_on:
    - logstash
    networks:
    - back1
    logging:
      driver: "syslog"
      options:
        tag: "desec/dblord"
#        syslog-address: "tcp://localhost:5000"

  dbmaster:
    build: dbmaster
    image: desec/dedyn-dbmaster:latest
    ports:
    - "3306:3306"
    volumes:
    - ${DESECSTACK_CERT_FOLDER}:/etc/ssl/private:ro
    - dbmaster_mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${DESECSTACK_DBMASTER_PASSWORD_root}
    - DESECSTACK_DBMASTER_PASSWORD_pdns
    - DESECSTACK_DBMASTER_PASSWORD_ns1replication
    - DESECSTACK_DBMASTER_SUBJECT_ns1replication
    - DESECSTACK_DBMASTER_PASSWORD_ns2replication
    - DESECSTACK_DBMASTER_SUBJECT_ns2replication
    depends_on:
    - logstash
    networks:
    - back1
    logging:
      driver: "syslog"
      options:
        tag: "desec/dbmaster"
#        syslog-address: "tcp://localhost:5000"

  api:
    build: api
    image: desec/dedyn-api:latest
    depends_on:
    - dbapi
    - nslord
    - logstash
    environment:
    - DESECSTACK_API_SECRETKEY
    - DESECSTACK_DBAPI_PASSWORD_desec
    - DESECSTACK_NSLORD_APIKEY
    volumes:
    - ./api-settings.py:/usr/src/app/desecapi/settings_local.py:ro
    networks:
    - back1
    - front # TODO change to back2 when https://github.com/docker/docker/issues/27101 is fixed
    logging:
      driver: "syslog"
      options:
        tag: "desec/api"
#        syslog-address: "tcp://localhost:5000"

  nslord:
    build: nslord
    image: desec/dedyn-nslord:latest
    environment:
    - DESECSTACK_DBLORD_PASSWORD_pdns
    - DESECSTACK_NSLORD_APIKEY
    depends_on:
    - dblord
    - logstash
    networks:
      back1:
        ipv4_address: 172.16.1.11
    logging:
      driver: "syslog"
      options:
        tag: "desec/nslord"
#        syslog-address: "tcp://localhost:5000"

  nsmaster:
    build: nsmaster
    image: desec/dedyn-nsmaster:latest
    environment:
    - DESECSTACK_DBMASTER_PASSWORD_pdns
    depends_on:
    - dbmaster
    - logstash
    networks:
      back1:
        ipv4_address: 172.16.1.12
    logging:
      driver: "syslog"
      options:
        tag: "desec/nsmaster"
#        syslog-address: "tcp://localhost:5000"

volumes:
  dbapi_mysql:
  dblord_mysql:
  dbmaster_mysql:

networks:
  back1: # TODO can we declare this internal? compose 1.9.0 will allow it: https://github.com/docker/compose/pull/3488 May break apt inside nslord etc.
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
  back2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24
        gateway: 172.16.2.1
  front:
    external: # TODO define network here when https://github.com/docker/compose/issues/3988 is fixed
      name: desecstack_front
