version: '2'

services:
  nslord:
    # extending from main .yml
    ports:
     - "5311:53"
     - "5311:53/udp"

  nsmaster:
    # extending from main .yml
    ports:
     - "5321:53"
     - "5321:53/udp"

  devadmin:
    build: devadmin
    environment:
    - DESECSTACK_DB_PASSWORD_poweradmin
    ports:
     - "81:80"
    networks:
    - back1
