ns:
  # extending from main .yml
  ports:
    - "5300:53"
    - "5300:53/udp"
    - "8081:8081"

poweradmin:
  build: desec-poweradmin
  links:
   - db
  ports:
   - "81:80"
  volumes:
   - ./desec-poweradmin/html:/var/www/html
   - ./desec-poweradmin/config.inc.php:/var/www/html/poweradmin/inc/config.inc.php
