version: '2'

services:
  www:
    build: desec-www
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./desec-certs/dev.desec.io:/etc/ssl/private
    depends_on:
    - static
    - api
    mac_address: 06:42:ac:11:00:01
    networks:
    - front

  static:
    build: desec-static
    networks:
    - front

  db:
    build: db
    ports:
    - "3306:3306"
    volumes:
    - ./desec-certs/dev.desec.io:/etc/ssl/private
    environment:
    - MYSQL_ROOT_PASSWORD=test123
    networks:
    - back

  api:
    build: api
    depends_on:
    - db
    - nslord
    volumes:
    - ./api-settings.py:/usr/src/app/desecapi/settings_local.py
    networks:
    - back
    - front

  nslord:
    build: nslord
    volumes:
    - ./nslord/conf:/etc/powerdns
    depends_on:
    - db
    networks:
      back:
        ipv4_address: 172.16.1.1

  nsmaster:
    build: nsmaster
    ports:
    - "53:53"
    volumes:
    - ./nsmaster/conf:/etc/powerdns
    depends_on:
    - db
    networks:
      back:
        ipv4_address: 172.16.1.2

networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/16
        gateway: 172.16.0.1
  front:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.15.0.0/16
        gateway: 172.15.0.1
