version: '2'

# mostly extending from main .yml
services:
 
  kibana:
    logging:
      driver: "none"

  elasticsearch:
    logging:
      driver: "none"
  
  logstash:
    logging:
      driver: "none"
 
  www:
    logging:
      driver: "json-file"

  static:
    logging:
      driver: "json-file"

  dbapi:
    logging:
      driver: "json-file"

  dblord:
    logging:
      driver: "json-file"

  dbmaster:
    logging:
      driver: "json-file"

  api:
    logging:
      driver: "json-file"

  nslord:
    ports:
     - "5311:53"
     - "5311:53/udp"
    logging:
      driver: "json-file"

  nsmaster:
    ports:
     - "5321:53"
     - "5321:53/udp"
    logging:
      driver: "json-file"

  # this container is dev-only
  devadmin:
    build: devadmin
    environment:
    - DESECSTACK_DBLORD_PASSWORD_poweradmin
    - DESECSTACK_DEVADMIN_SESSIONKEY_poweradmin
    ports:
     - "127.0.0.1:81:80"
    networks:
    - back1
