version: '2'

services:
  www:
    build: www
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ${DESECSTACK_CERT_FOLDER}:/etc/ssl/private:ro
    - ./www/html:/usr/share/nginx/html:ro
    depends_on:
    - static
    - api
    mac_address: 06:42:ac:10:00:80
    networks:
      front:
        ipv4_address: 172.16.0.128
        ipv6_address: ${DESECSTACK_IPV6_ADDRESS}
#      - back2 # TODO add when https://github.com/docker/docker/issues/27101 is fixed

  static:
    build: static
    networks:
    - front # TODO change to back2 when https://github.com/docker/docker/issues/27101 is fixed

  dbapi:
    build: dbapi
    volumes:
    - dbapi_mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${DESECSTACK_DBAPI_PASSWORD_root}
    - DESECSTACK_DBAPI_PASSWORD_desec
    networks:
    - back1

  dblord:
    build: dblord
    volumes:
    - dblord_mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${DESECSTACK_DBLORD_PASSWORD_root}
    - DESECSTACK_DBLORD_PASSWORD_pdns
    - DESECSTACK_DBLORD_PASSWORD_poweradmin
    - DESECSTACK_DEVADMIN_PASSWORD_poweradmin
    networks:
    - back1

  dbmaster:
    build: dbmaster
    ports:
    - "3306:3306"
    volumes:
    - ${DESECSTACK_CERT_FOLDER}:/etc/ssl/private:ro
    - dbmaster_mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${DESECSTACK_DBMASTER_PASSWORD_root}
    - DESECSTACK_DBMASTER_PASSWORD_pdns
    - DESECSTACK_DBMASTER_PASSWORD_ns1replication
    - DESECSTACK_DBMASTER_SUBJECT_ns1replication
    - DESECSTACK_DBMASTER_PASSWORD_ns2replication
    - DESECSTACK_DBMASTER_SUBJECT_ns2replication
    networks:
    - back1

  api:
    build: api
    depends_on:
    - dbapi
    - nslord
    environment:
    - DESECSTACK_API_SECRETKEY
    - DESECSTACK_DBAPI_PASSWORD_desec
    - DESECSTACK_NSLORD_APIKEY
    volumes:
    - ./api-settings.py:/usr/src/app/desecapi/settings_local.py:ro
    networks:
    - back1
    - front # TODO change to back2 when https://github.com/docker/docker/issues/27101 is fixed

  nslord:
    build: nslord
    environment:
    - DESECSTACK_DBLORD_PASSWORD_pdns
    - DESECSTACK_NSLORD_APIKEY
    depends_on:
    - dblord
    networks:
      back1:
        ipv4_address: 172.16.1.11

  nsmaster:
    build: nsmaster
    environment:
    - DESECSTACK_DBMASTER_PASSWORD_pdns
    depends_on:
    - dbmaster
    networks:
      back1:
        ipv4_address: 172.16.1.12

volumes:
  dbapi_mysql:
  dblord_mysql:
  dbmaster_mysql:

networks:
  back1: # TODO can we declare this internal? compose 1.9.0 will allow it: https://github.com/docker/compose/pull/3488 May break apt inside nslord etc.
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
  back2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24
        gateway: 172.16.2.1
  front:
    external: # TODO define network here when https://github.com/docker/compose/issues/3988 is fixed
      name: desecstack_front
