version: '2'

services:
  www:
    build: www
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./certs/dev.desec.io:/etc/ssl/private
    depends_on:
    - static
    - api
    mac_address: 06:42:ac:10:00:80
    networks:
      front:
        ipv4_address: 172.16.0.128
        ipv6_address: 2a01:4f8:a0:12eb:deec:0642:ac10:0080
#      - back2 # TODO add when https://github.com/docker/docker/issues/27101 is fixed

  static:
    build: static
    networks:
    - front # TODO change to back2 when https://github.com/docker/docker/issues/27101 is fixed

  db:
    build: db
    ports:
    - "3306:3306"
    volumes:
    - ./certs/dev.desec.io:/etc/ssl/private
    environment:
    - MYSQL_ROOT_PASSWORD=test123
    networks:
    - back1

  api:
    build: api
    depends_on:
    - db
    - nslord
    volumes:
    - ./api-settings.py:/usr/src/app/desecapi/settings_local.py
    networks:
    - back1
    - front # TODO change to back2 when https://github.com/docker/docker/issues/27101 is fixed

  nslord:
    build: nslord
    volumes:
    - ./nslord/conf:/etc/powerdns
    - ./nslord/cronhook/insecure-zones.list:/root/cronhook/insecure-zones.list
    - ./nslord/cronhook/my.cnf:/root/cronhook/my.cnf
    depends_on:
    - db
    networks:
      back1:
        ipv4_address: 172.16.1.11

  nsmaster:
    build: nsmaster
    volumes:
    - ./nsmaster/conf:/etc/powerdns
    depends_on:
    - db
    networks:
      back1:
        ipv4_address: 172.16.1.12

networks:
  back1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
  back2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24
        gateway: 172.16.2.1
  front:
    external: # TODO define network here when https://github.com/docker/compose/issues/3988 is fixed
      name: desecstack_front
