www:
  build: desec-www
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./desec-certs/dev.desec.io:/etc/ssl/private
  links:
   - static
   - api
  mac_address: 06:42:ac:11:00:01

static:
  build: desec-static

db:
  build: desec-db
  environment:
   - MYSQL_ROOT_PASSWORD=test123

api:
  build: desec-api
  links:
   - db
   - ns
  volumes:
   - ./api-settings.py:/usr/src/app/desecapi/settings_local.py

ns:
  build: desec-ns
  links:
   - db
