version: '2'

services:
  nslord:
    # extending from main .yml
    ports:
     - "5311:53"
     - "5311:53/udp"

  nsmaster:
    # extending from main .yml
    ports:
     - "5321:53"
     - "5321:53/udp"

  devadmin:
    build: devadmin
    ports:
     - "81:80"
    volumes:
     - ./devadmin/html:/var/www/html:ro
     - ./devadmin/config.inc.php:/var/www/html/poweradmin/inc/config.inc.php:ro
    networks:
    - back1
